### ISSUE TITLE
Incorrect token generation in Watson docs

### ISSUE THREAD

**Issue by MartinSmolny** [ibm-cloud-docs/watson#47]
https://cloud.ibm.com/docs/services/watson?topic=watson-iam#iamtoken

The first call to get an IAM token is basically correct, but is using the deprecated URL `iam.bluemix.net`. The second call is incorrect.

Please compare with this section from the IAM team:
https://cloud.ibm.com/docs/iam?topic=iam-iamtoken_from_apikey

Note that there is no refresh case described - in the API key case, there is no refresh token necessary, the user should always request a new access token using the API key.

**Comment by SirSpidey** [comment]
Thanks @MartinSmolny. I've updated the bluemix URL. We'll remove the refresh examples and update the content soon.

**Comment by SirSpidey** [comment]
Refresh token examples are gone with updates about full IAM support.
