### ISSUE TITLE
IAM token example does not allow for refreshing tokens

### ISSUE THREAD

**Issue by timl1** [ibm-cloud-docs/watson#50]
The documentation is a bit confusing with the first 2 curl commands in the "Getting an IAM token by using a Watson service API key" section.  The first curl command to get the IAM token does work, but the issue is later on when you refresh the token, it fails due to a mismatched Authorization header.  If instead you use the 2nd curl command, then the refresh token call works.  Is there a need to have the 1st curl command documented here, or should that be removed and all IAM token calls just use the 2nd command with --header "Authorization: Basic Yng6Yng=" ?  Seems to be simpler and a best practice to always pass the Authorization header if it's just a hardcoded literal for the CLI and allows you to refresh your token

**Comment by SirSpidey** [comment]
Thanks @timl1 We will be updating this page. We plan to remove the info about refreshing an existing token just request a new access token using the API key.

**Comment by SirSpidey** [comment]
Refresh token examples are gone with updates about full IAM support.
