### ISSUE TITLE
IBM Watson Python docs

### ISSUE THREAD

**Issue by wmbbarnett** [ibm-cloud-docs/watson#58]
documentation says: "pip install --upgrade ibm-watson" but should say: "pip3 install --upgrade ibm-watson"

**Comment by SirSpidey** [comment]
@wmbbarnett Oh no! Mr. Bill! 

I think that pip works for whichever environment you have set up, although pip3 is specific to python3. I'll check with the SDK developers about this command.

**Comment by SirSpidey** [comment]
Thanks for checking on this. We've decided to leave the command as is. You do need to have a Python3 environment set up, however.
