### ISSUE TITLE
Incorrect labels and procedure for BYOK Premium provisioning

### ISSUE THREAD

**Issue by dtoczala** [ibm-cloud-docs/watson#62]
On this page - https://cloud.ibm.com/docs/speech-to-text?topic=watson-keyservice#keyservice-about

Step 3 reads like this:

### Grant service access to Key Protect
After you add a root key to Key Protect, you use Cloud Identity and Access Management (IAM) to authorize access between the Watson service and Key Protect.
You must be the account owner or administrator on the Key Protect service instance and at least the viewer role on all instances of the Watson services.

1. Go to the IAM Authorizations page. (From the IBM Cloud console menu bar, select Manage > Access IAM, and then click Authorizations.)
2. Select the Watson service as the Source service. Leave All instances selected.
3. Select the key that you added earlier as the Target service instance.
4. Select the Key Protect as the target service and then select the key that you added earlier as the target service instance.
5. Authorize dependent services by selecting Enable authorization to be delegated.
 Delegation allows the Key Protect instance to propagate its authorizations to this service.
6. Make sure that the Reader role in enabled.
 Reader permissions allow the Watson service to see the root keys in the Key Protect instance.
7. Click Authorize and confirm delegated authorization.

Step 3 **SHOULD** read like this: (fixes are in _**bold italics**_)

### Grant service access to Key Protect
After you add a root key to Key Protect, you use Cloud Identity and Access Management (IAM) to authorize access between the Watson service and Key Protect.
You must be the account owner or administrator on the Key Protect service instance and at least the viewer role on all instances of the Watson services.

1. Go to the IAM Authorizations page. (From the IBM Cloud console menu bar, select Manage > Access IAM, and then click Authorizations.). **_Click on the Create button._**
2. Select the Watson service as the Source service. Leave **_All Resources_** selected.
3. Select the **_Key Protect service_** that you added earlier as the Target service instance **_and select Resources based on selected attributes._**
4. Select **_Instance ID as the target service attribute_**, and then select the **_Key Protect service_** that you added earlier as the target service instance.
5. Authorize dependent services by selecting Enable authorization to be delegated.
 Delegation allows the Key Protect instance to propagate its authorizations to this service.
6. Make sure that the Reader role **_is_** enabled.
 Reader permissions allow the Watson service to see the root keys in the Key Protect instance.
7. Click Authorize and confirm delegated authorization.

**Comment by SirSpidey** [comment]
Thanks @dtoczala. Created an internal issue and poked you in it.

**Comment by SirSpidey** [comment]
In production
