### ISSUE TITLE
Incorrect grammar 

### ISSUE THREAD

**Issue by jigneshkvp** [ibm-cloud-docs/watson#65]
In the following section: [Authenticating to Watson services](https://cloud.ibm.com/docs/watson?topic=watson-iam#gs-credential-cloud) the grammar of a sentence is incorrect under "Authenticate with IAM tokens". 

The grammatical error is in line  
_The following Curl command generates **and** IAM access token_ 

Should be 
_The following Curl command generates **an** IAM access token_

**Comment by jeffpk62** [comment]
Hi, @jigneshkvp.  Thanks for spotting this.  It's less incorrect grammar than a dumb typo. :-)  I'm fixing it now and will have it updated in production soon.  Thank you again!

**Comment by jeffpk62** [comment]
It's building in production now.  Thanks again!
